Management/Areas/WebContent/Models/NEWS/NEWSModel .cs
using DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Utility.Files;

namespace Management.Areas.WebContent.Models
{
    public class NEWSModel : NewsDefaultModel
    {
        public string WebSiteId { get; set; }
        public List<AuthSysGroupWebLevel> AuthSysGroupWebLevels { get; set; }
    }
}

Management/Areas/WebContent/Models/NEWS/PageViewModel.cs
using DBModel;
using Services.Models;
using Services.Models.WebSite;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Management.Areas.WebContent.Models.WebLevelManagement
{
    public class PageViewModel
    {
        public class News
        {
            public  WebNewsDetailModel webNewsDetailModel { get; set; } = new WebNewsDetailModel();
            /// <summary>
            /// WebNewsDetailModel
            /// </summary>
            public class WebNewsDetailModel
            {
                //基本資訊，EX標題、內容、內容模式、URL.....
                public WEBNews BasicData;
                //相關檔案、圖片
                public Attachment attachment;

                public List<WebLink> webLinks;

                public struct Attachment
                {
                    /// <summary>
                    /// 網頁模式
                    /// </summary>
                    public Page page;

                    /// <summary>
                    /// 檔案下載模式
                    /// </summary>
                    public Download download;
                }

                public struct Page
                {
                    /// <summary>
                    /// 相關檔案
                    /// </summary>
                    public List<WebFileAndGroupIDModel> Files;

                    /// <summary>
                    /// 相關圖檔
                    /// </summary>
                    public List<WebFileAndGroupIDModel> Imgs;

                }

                public struct Download
                {
                    /// <summary>
                    /// 單檔下載
                    /// </summary>
                    public WebFileAndGroupIDModel File;
                }
            }
            public WebLevel parentData { get; set; }
            public WebLevel localWebLevel { get; set; }
            public List<PAGELISTModel> brotherData { get; set; }
            public string DepName { get; set; }

            public List<WebLevelModel> Breadcrumb { get; set; }
        }
        //
    }


}

Management/Areas/WebContent/Controllers/NEWSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBModel;
using Management.Areas.WebContent.Models;
using Management.Areas.WebContent.Models.WebLevelManagement;
using Management.ManagementUtility;
using Management.Models.Common;
using Microsoft.AspNetCore.Mvc;
using Services;
using Services.Authorization;
using Services.Models;
using Services.Models.WebSite;
using Services.WebManagement;
using Services.WebSite;
using static Utility.Files;

namespace Management.Areas.WebContent.Controllers
{

    [Area("WebContent")]
    public class NEWSController : BaseController
    {
        public IActionResult Index(string key = "", string key2 = "")
        {
            var _key = 0;
            if (int.TryParse(key, out _key))
            {
                SetSession("WEBFile", new List<CommonFileModel>());
                var fileData = new List<CommonFileModel>();
                Models.NEWSModel viewModel = new Models.NEWSModel();
                DBModel.WEBNews wEBNews = new DBModel.WEBNews();
                wEBNews.DepartmentID = UserData.sysUser.DepartmentID;
                wEBNews.ArticleType = "0";
                viewModel.wEBNews = wEBNews;
                viewModel.webLevel = WebLevelManagementService.GetWebLevel(_key);
                viewModel.sysWebSiteLangs = WebLevelManagementService.GetSysWebSiteLangs(UserData, "", 0);
                viewModel.AuthSysGroupWebLevels = UserData.webLevelAccessForGroups.Where(x => x.WebLevelSN == _key).ToList();
                viewModel.sysUserSysDepartmentID = UserData.sysUser.DepartmentID;
                if (!string.IsNullOrWhiteSpace(key2))
                {
                    var _key2 = 0;
                    if (int.TryParse(key2, out _key2))
                    {
                        var LangDataList = WebLevelManagementService.GetWEBNewByMainSN(_key2);
                        var ZH_Transcript = NewsService.GetWEBNewsTranscript(LangDataList.First(x=>x.Lang=="zh-tw").WEBNewsSN);
                        var en_Transcript = NewsService.GetWEBNewsTranscript(LangDataList.First(x => x.Lang == "en").WEBNewsSN);
                        SetSession($"MD_Datazh-tw", ZH_Transcript);
                        SetSession($"MD_Dataen", en_Transcript);
                        foreach (var langData in LangDataList)
                        {
                            var CommonModel = new NewCommonModel();
                            CommonModel.webNews = langData;
                            CommonModel.wEBNewsExtends = WebLevelManagementService.GetWEBNewsExtends(langData.WEBNewsSN);
                            CommonModel.AuthSysGroupWebLevels = UserData.webLevelAccessForGroups.Where(x => x.WebLevelSN == _key).ToList(); ;
                            var files = CommonUtility.GetFileByDB(langData.WEBNewsSN.ToString(), "WEBNews");
                            if (files != null)
                            {
                                foreach (var f in files)
                                {
                                    f.lan = langData.Lang;
                                }
                                CommonModel.commonFileModels = files;
                                fileData.AddRange(files);
                            }
                            CommonModel.sysUserSysDepartmentID = UserData.sysUser.DepartmentID;
                            viewModel.newCommonModels.Add(CommonModel);
                        }
                        viewModel.wEBNews = LangDataList.First();
                        viewModel.LevelBreadcrumb = CommonService.LevelBreadcrumb(_key, _key2);
                    }
                    else
                    {
                        return View(null);
                    }
                }
                else
                {
                    viewModel.LevelBreadcrumb = CommonService.LevelBreadcrumb(_key);
                }
                SetSession("WEBFile", fileData);
                viewModel.WebSiteId = UserData.WebSiteID;
                return View(viewModel);
            }
            return View(null);
        }

        /// <summary>
        /// 中繼站
        /// </summary>
        /// <param name="key">WebLevelMSN</param>
        /// <param name="key2">WEBNewsSN</param>
        /// <returns></returns>
        public IActionResult NewsType(string key = "", string key2 = "", string key3 = "")
        {
            return RedirectToAction("Index", new { area = "WebContent", Controller = key3, key = key, key2 = key2 });
        }
        /// <summary>
        /// 公版WEBNES儲存功能
        /// </summary>
        /// <param name="wEBNews">webNEWS </param>
        /// <param name="fileinfo">檔案排序</param>
        /// <param name="linkinfo">這個要移除</param>
        /// <param name="tab">主題標籤</param>
        /// <param name="keyword">關鍵字</param>
        /// <param name="whole">整體績效</param>
        /// <param name="policy">政策計畫</param>
        /// <param name="business">業務分類</param>
        /// <param name="serve">服務對象</param>
        /// <param name="relatedlink">相關連結</param>
        /// <param name="relatedvideo">相關影片</param>
        /// <param name="relatedmoj">相關法規</param>
        /// <returns></returns>
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult WEBNewsSave(
            WEBNews wEBNews,
            List<CommonFileModel> fileinfo = null,
            List<WebLink> linkinfo = null,
            List<string> tab = null,
            List<SelectTxt> keyword = null,
            List<string> whole = null,
            List<string> policy = null,
            List<string> business = null,
            List<string> serve = null,
            List<SelectTxt> relatedlink = null,
            List<SelectTxt> relatedvideo = null,
            List<SelectTxt> relatedmoj = null
            )
        {
            try
            {
                SetLogActionModel(webPath: "網站維護/" + OperationStatisticsService.GetWebLevelTree(wEBNews.WebLevelSN).FirstOrDefault()?.Path, Action2: wEBNews.WEBNewsSN == 0 ? Utility.Model.LoginModel.Action2.insert : Utility.Model.LoginModel.Action2.update, SourceTable: "WEBNews");
                wEBNews.WebSiteID = UserData.WebSiteID;
                wEBNews.CreatedUserID = UserData.sysUser.UserID;
                var ReviewerState = wEBNews.IsEnable;
                var MailProcessUserID = wEBNews.ProcessUserID;

                if(wEBNews.IsEnable != "-2")
                {   
                    if(wEBNews.IsEnable == "4")
                    {
                        wEBNews.IsEnable = "1";
                    }
                    wEBNews.ProcessUserID = UserData.sysUser.UserID;
                }

                wEBNews.CreatedDate = DateTime.UtcNow.AddHours(8);
                wEBNews.PublishDate = DateTime.UtcNow.AddHours(8);
                wEBNews.ProcessIPAddress = ContextModel.ProcessIpaddress;
                wEBNews.DepartmentID = wEBNews.DepartmentID;
                var WEBNewsExtendData = new List<WEBNewsExtend>();

                #region 擴充表資料整理
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(tab, "tab"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(keyword, "keyword"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(whole, "whole"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(policy, "policy"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(business, "business"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(serve, "serve"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(relatedlink, "relatedlink"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(relatedvideo, "relatedvideo"));
                WEBNewsExtendData.AddRange(GetWEBNewsExtend(relatedmoj, "relatedmoj"));
                #endregion

                var files = GetSession<List<CommonFileModel>>("WEBFile");
                if (fileinfo.Count() > 0 && fileinfo.Where(x => x.lan == wEBNews.Lang) != null && files.Where(x => x.lan == wEBNews.Lang) != null)
                {
                    foreach (var file in files.Where(x => x.lan == wEBNews.Lang))
                    {
                        var fileModel = fileinfo.FirstOrDefault(x => x.fileNewName == file.fileNewName);
                        if (fileModel != null)
                        {
                            file.fileTitle = fileModel.fileTitle;
                            file.FileSort = fileModel.FileSort;
                        }
                    }
                }
                var Transcript = new List<WEBNewsTranscript>();
                Transcript = GetSession<List<WEBNewsTranscript>>($"MD_Data{wEBNews.Lang}");

                if (wEBNews.Module == Utility.EnumTpye.GetEnumName(Utility.SysConst.Module.NEWS) || wEBNews.Module == Utility.EnumTpye.GetEnumName(Utility.SysConst.Module.CP))
                {
                    string lang = wEBNews.Lang;
                    if (wEBNews.ArticleType != Utility.EnumTpye.GetEnumNumberToSting(Utility.SYSConst.Content.Type.PAGE))
                    {
                        wEBNews.PageViewType = null;
                        wEBNews.ContentText = null;
                        files.RemoveAll(x => x.GroupID == Utility.WebFileGroupID.News.InlineImgs && x.lan == lang);
                        files.RemoveAll(x => x.GroupID == Utility.WebFileGroupID.News.Files && x.lan == lang);
                        files.RemoveAll(x => x.GroupID == Utility.WebFileGroupID.News.Imgs && x.lan == lang);
                        WEBNewsExtendData.RemoveAll(x => x.GroupID == "relatedlink");
                        WEBNewsExtendData.RemoveAll(x => x.GroupID == "relatedvideo");
                        WEBNewsExtendData.RemoveAll(x => x.GroupID == "relatedmoj");
                    }

                    if (wEBNews.ArticleType != Utility.EnumTpye.GetEnumNumberToSting(Utility.SYSConst.Content.Type.DOWNLOAD))
                    {

Management/Areas/WebContent/Views/NEWS/Index.cshtml
@model Management.Areas.WebContent.Models.NEWSModel

<div class="bootstrap-table">
    <partial name="~/Views/Common/Breadcrumb.cshtml" model=Model.LevelBreadcrumb />
    @if (Model.newCommonModels.Count() > 0)
    {
        <ul class="nav nav-tabs customtab" id="myTab" role="tablist">
            @foreach (var lan in Model.sysWebSiteLangs)
            {
                <li class="nav-item">
                    <a href="#@lan.Lang" class="nav-link @(lan.Lang=="zh-tw" ?" active":"")" id="authority-tab" data-bs-toggle="tab" data-bs-target="#@lan.Lang" role="tab" aria-controls="@lan.Lang" aria-selected="false">@(lan.Lang == "zh-tw"?"中文":"英文")</a>
                </li>
            }
        </ul>
    }
    <hr />
    <div class="form-horizontal tab-content">
        @if (Model.newCommonModels.Count() == 0)
        {
            var newCommonModel = new NewCommonModel() { webNews = new WEBNews() { Lang = "zh-tw", WebSiteID = Model.WebSiteId, WebLevelSN = Model.webLevel.WebLevelSN }, AuthSysGroupWebLevels = Model.AuthSysGroupWebLevels  , sysUserSysDepartmentID = Model.sysUserSysDepartmentID };
            <partial name="~/Areas/WebContent/Views/NEWS/ModeView.cshtml" model="newCommonModel" />
        }
        else
        {
            foreach (var lan in Model.newCommonModels)
            {
                <partial name="~/Areas/WebContent/Views/NEWS/ModeView.cshtml" model="lan" />
            }
        }
    </div>
</div>
@Html.AntiForgeryToken()
<script>
    changeArticleType('zh-tw');
    changeArticleType('en');
    function changeArticleType(lan) {
        var name = "ArticleType" + lan;
        var ArticleType = MODAhtmlEncode($('input[name=' + name + ']:checked'), "val");
        $("#ArticleType_0" + lan).hide();
        $(".ArticleType_0" + lan).hide();
        $("#ArticleType_1" + lan).hide();
        $("#ArticleType_2" + lan).hide();
        $("#ArticleType_10" + lan).hide();
        $("#ArticleType_" + ArticleType + lan).show();
        $(".ArticleType_" + ArticleType + lan).show();
    }
    function Save(IsEnable, lan) {
        var name = "ArticleType" + lan;
        var ArticleType = MODAhtmlEncode($('input[name=' + name + ']:checked'), "val");      
        var isEnable = "";
        if (IsEnable == "4" || IsEnable == "-2" || IsEnable == "-1") {
            isEnable = IsEnable;
        }
        else{
            isEnable = MODAhtmlEncode($('input[name=IsEnable' + lan + ']:checked'), "val");
        }

        if (IsEnable == "-1" && (ArticleType == "1" || ArticleType == "2")) {
            Swal.fire({
                icon: "warning",
                title: "只有一般資料/逐字稿 格式才有預覽功能"
            });
            return false;
        }
        var tab = $("#tab" + lan).val();
        var whole = $("#whole" + lan).val();
        var policy = $("#policy" + lan).val();
        var business = $("#business" + lan).val();
        var serve = $("#serve" + lan).val();
        var keyword = txtAreaObj("key" + lan);
        var relatedlink = [];
        var relatedvideo = [];
        var relatedmoj = [];
        var seodescription = MODAhtmlEncode($("[name='SEODescription" + lan + "']"), "val");
        var seokeywords = MODAhtmlEncode($("[name='SEOKeywords" + lan + "']"), "val");
        var saveHref = '@Url.Action("WEBNewsSave", "NEWS", new { area = "WebContent" })';
        if (IsEnable == "-1") {
            saveHref = '@Url.Action("news", "Demo", new { area = "WebContent" })';
        }
        var contenttext = "";
        var url = "";
        switch ($('input[name=ArticleType' + lan + ']:checked').val()) {
            case "0": //一般
                contenttext = lan == "en" ? CKEDITOR.instances.editoren.getData() : CKEDITOR.instances.editorzhtw.getData();
                relatedlink = txtAreaObj("link" + lan);
                relatedvideo = txtAreaObj("video" + lan);
                relatedmoj = txtAreaObj("moj" + lan);
                break;
            case "1": //檔案下載
                break;
            case "2": //Url
                url = $("#URL" + lan).val();
                break;
            case "10":
                relatedlink = txtAreaObj("link" + lan);
                relatedvideo = txtAreaObj("video" + lan);
                relatedmoj = txtAreaObj("moj" + lan);
                break;
        }

        var d = [{ link: relatedlink, video: relatedvideo, moj: relatedmoj, key: keyword }];
        var msg = "";
        $.each(d, function(index, item) {
            $.each(item, function(iidex, iitem) {
                if (iitem.filter(x => x.txt == "" || x.val == "").length > 0) {
                    msg += "請完整輸入" + (iidex == "link" ? "[相關連結]" : iidex == "video" ? "[相關影片]" : iidex == "moj" ? "[相關法規]" : iidex == "key" ? "[關鍵字]" : "") + "所需欄位\n";
                }
            });
        });

        if (msg != "") {
            Swal.fire({
                icon: "warning",
                info: msg
            });
            return false;
        }

        var key = @Model.webLevel.WebLevelSN;
        var key2 = @(Model.wEBNews == null? 0 : Model.wEBNews.WEBNewsSN);
        var ct = '@(Model.webLevel.ListType)' =="ImageTextList" ? $("#Title" + lan).val() :  contenttext ;
        var obj = {
            webNewssn: '@(Model.wEBNews == null? 0 : Model.wEBNews.WEBNewsSN)',
            weblevelsn: '@(Model.webLevel.WebLevelSN)',
            module: '@(Model.webLevel.Module)',
            articletype: $('input[name=ArticleType' + lan + ']:checked').val(),
            title: $("#Title" + lan).val(),
            subtitle: $("#SubTitle" + lan).val(),
            description: "",
            DepartmentID: $('#dep' + lan).val(),
            contenttext: ct,
            url: url,
            target: $('input[name=target' + lan + ']:checked').val(),
            youtubeid: "",
            istop: $('select[name=IsTop' + lan + '] option:selected').val(),
            isenable: isEnable,
            startdate: $("#StartDate" + lan).val(),
            enddate: $("#EndDate" + lan).val(),
            fileinfo: fileinfo(lan),
            lang: lan,
            tab: JSON.parse(tab),
            whole: JSON.parse(whole),
            policy: JSON.parse(policy),
            business: JSON.parse(business),
            serve: JSON.parse(serve),
            keyword: keyword,
            relatedlink: relatedlink,
            relatedvideo: relatedvideo,
            relatedmoj: relatedmoj,
            customizetagSn: $('select[name=customize' + lan + '] option:selected').val(),
            seodescription: seodescription,
            seokeywords: seokeywords,
            processuserid : '@(Model.wEBNews == null ? null : Model.wEBNews.ProcessUserID)' 
        };
        if (isEnable == "1" || isEnable == "0") {
            Swal.fire({
                title: '確定要儲存?',
                icon: 'warning',
                showDenyButton: true,
                showCancelButton: false,
                confirmButtonText: '確定',
                denyButtonText: '取消',
            }).then((result) => {
                if (result.isConfirmed) {
                    SaveNews(obj, saveHref, IsEnable);
                } else if (result.isDenied) {
                    Swal.fire('已取消!', '', 'info')
                }
            })
        }
        else if (isEnable == "4" || isEnable == "3") {
            var content = IsEnable == "4" ? "送審確定送出?" : "確定要送審?"
            Swal.fire({
                title: content,
                icon: 'warning',
                showDenyButton: true,
                showCancelButton: false,
                confirmButtonText: '確定',
                denyButtonText: '取消',
            }).then((result) => {
                if (result.isConfirmed) {
                    SaveNews(obj, saveHref, IsEnable);
                } else if (result.isDenied) {
                    Swal.fire('已取消!', '', 'info')
                }
            })
        }
        else {
            SaveNews(obj, saveHref, IsEnable);
        }
    }
    function SaveNews(obj, saveHref, IsEnable) {
        $('.preloader').show();
        $.ajax({
            url: saveHref,
            type: 'post',
            data: obj,
            headers:
            {
                "CUSTOMER-CSRF-HEADER": $("input[name='CustomerFieldName']").val() //注意header要修改
            },
            dataType: "json",
            success: function(data) {
                $('.preloader').hide();
                if (data.statusCode == 200) {
                    if (IsEnable == -1) {
                        window.open("@Url.Action("PageView", "Demo", new { area = "WebContent" })", "temp", config = 'height=800,width=1204');
                    } else {
                        Swal.fire({
                            icon: "success",
                            title: "更新成功"
                        });
                        backward();
                    }
                }
                else {
                    Swal.fire({
                        icon: "warning",
                        title: data.content
                    });

                }
            }
        });
    }
    function CPFun(key, key2) {
        var href = "@Url.Action("Index", "NEWS", new { area = "WebContent" })?key=" + key + "&key2=" + key2;
        $("#fox_box").load(href, function() { });
    }
    function backward() {
        var href = "@Url.Action("Article", "WebLevelManagement", new { area = "WebContent" ,  key= CommonUtility.GetUrlAesEncrypt(Model.webLevel.WebLevelSN.ToString()) }   )";
        $("#fox_box").load(href, function() { });
    }

    function DeleteLink(e) {
        var tr = e.closest("tr");
        tr.remove();
    }

    function DepSelector() {
        $("#DepArea").load("@Url.Action("CommonDepartment", "Common", new { area = "" })", function() {
                DepartmentSelectorTrigger().then(function(result) {
                    var DepData = JSON.parse(result);
                    $('#dep').data('id', DepData.DepID);
                    $('#dep').html(DepData.DepName);
                })
        });
    }
    function GetDepartment() {
        if ($('#dep').data('id')) {
            $.ajax({
                url: '@Url.Action("GetDepartment", "Common", new { area = "" })',
                type: 'post',
                headers:
                {
                    "CUSTOMER-CSRF-HEADER": $("input[name='CustomerFieldName']").val() //注意header要修改
                },
                data: {
                    depID: $('#dep').data('id'),
                },
                dataType: "json",
                success: function(data) {
                    $('#dep').html(data.content);
                }
            });
        }
    }

    function txtAreaObj(Name) {
        var array = [];
        $.each($(".class" + Name), function() {
            var val = $(this).find(".classval" + Name).val() == undefined ? null : $(this).find(".classval" + Name).val();
            var txt = $(this).find(".classtxt" + Name).val();
            array.push({ val: val, txt: txt });
        });
        return array;
    }
</script>