Management/Areas/MailBox/Models/SpeedLog/ListModel.cs
using Services.Models.ModaMailBox;
using System.Collections.Generic;
using Utility;

namespace Management.Areas.MailBox.Models.SpeedLog
{
    public class ListModel
    {
        public List<SpeedLogModel> SpeedLogs { get; set; }
        public DefaultPager defaultPager { get; set; }
    }
}

Management/Areas/MailBox/Controllers/SpeedLogController.cs
using Management.ManagementUtility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Services.ModaMailBox;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Utility;

namespace Management.Areas.MailBox.Controllers
{
    [Area("MailBox")]
    public class SpeedLogController : BaseController
    {
        private readonly Microsoft.AspNetCore.Hosting.IWebHostEnvironment _hostingEnvironment;
        public SpeedLogController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        /// <summary>
        /// api Log
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            ViewData["Breadcrumb"] = CommonUtility.Breadcrumb(31);
            if (!CheckUserMenu(31).chk) { return RedirectToAction("ErrorCome", "Home", new { area = "" }); }

            return View();
        }

        public IActionResult List(string cn , string strDate, string endDate, int p = 1, int displayCount = 10 )
        {
            var ListModels = new Models.SpeedLog.ListModel();
            var websiteId = "";
            DefaultPager pager = new DefaultPager();
            pager.DisplayCount = displayCount;
            pager.p = p;
            var lists = MailBoxService.GetSpeedLog(websiteId, strDate, endDate, cn, ref pager);

            ListModels.defaultPager = pager;
            ListModels.SpeedLogs = lists;
            return View(ListModels);
        }

        public IActionResult ExcelReport(string strDate, string endDate , string cn)
        {
            var websiteId = "";
            var fileName = $@"API紀錄表{DateTime.UtcNow.AddHours(8).ToString("yyyyMMdd")}.xlsx";
            try
            {
                var path = _hostingEnvironment.WebRootPath;
                var excelDatas = new MemoryStream();
                DefaultPager pager = new DefaultPager();

                var list = MailBoxService.GetSpeedLog(websiteId, strDate, endDate,cn);
                var filePath = $@"{path}/Temp/UserReport.xlsx";
                var Info = new List<string>() {
                    $@"製表日期: {DateTime.UtcNow.AddHours(8).ToString("yyyy-MM-dd HH:mm")}",
                    $@"製表人: {UserData?.sysUser.UserName}",
                    $@"資料筆數: {list.Count}"
                };
                var DetailTitle = new List<string>() {
                    "案件編號",
                    "API請求",
                    "請求狀態",
                    "請求內容",
                    "API回應狀態",
                    "API回應訊息",
                    "API回應內容",
                    "請求時間",
                    "使用者"
                };
                var EModel = new ExcelModel();
                EModel.Title = "民意信箱API紀錄表";
                EModel.Info = Info;
                EModel.DetailTitle = DetailTitle;
                EModel.ExcelDetails = list.Select(x => new ExcelDetailModel()
                {
                    a = x.CaseNo,
                    b = x.Action,
                    c = x.Success,
                    d = x.Requset,
                    e = x.ApiStatus,
                    f = x.ApiMessage,
                    g = x.Message,
                    h = x.CreateDate.ToString("yyyy-MM-dd HH:mm"),
                    i = x.CreateUser
                }
                ).ToList();
                excelDatas = Utility.Output.ExampleReport(EModel, filePath);

                return File(excelDatas.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{fileName}");
            }
            catch (Exception ex)
            {
                IList<string> errmsgs = new List<string>();
                string error = "";
                error = ex.Message;
                errmsgs.Add(error);
                return File(System.Text.Encoding.UTF8.GetBytes(error), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{fileName}");
            }
        }
    }
}

Management/Areas/MailBox/Views/SpeedLog/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <div class="bootstrap-table">
                <div class="row searchBar1">
                <div class="col">
                    <label class="col-form-label">
                        案件編號/公文文號：
                    </label>
                        <input type="text" id="caseno" class="form-control" placeholder="案件編號/公文文號">
                    </div>
                    <div class="col col-dateToDate dateW3">
                        <label class="col-form-label">
                            日期區間：
                        </label>
                        <div class="row">
                            <div class="col">
                                <div class="row">
                                    <div class="col">  <input type="date" id="strDate" class="form-control" placeholder="開始時間"></div>
                                    <div class="col">~</div>
                                    <div class="col">  <input type="date" id="endDate" class="form-control" placeholder="結束時間"></div>
                                </div>
                            </div>
                            <div class="col">
                                @{
                                    var btns = new List<btnModel>();
                                    btns.Add(new btnModel() { Btntype = btnModel.btntype.查詢, onclickFunction = "searchFunction(1)", IdName = "searchBtn" });
                                    btns.Add(new btnModel() { Btntype = btnModel.btntype.匯出, onclickFunction = "exportFun()", IdName = "exportBtn" });
                                        <partial name="~/Views/Common/Btn/BtnPublicVersion.cshtml" model="btns" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uTable3">
                    <div id="tableList"></div>
                </div>
            </div>
            <div id="DepArea"></div>
        </div>
    </div>
</div>
@section scripts{
<script>
    var href = "@Url.Action("List", "SpeedLog", new { area = "MailBox" })";
    $(document).on("click", ".page_a", function () {
        var p = getObjAtr($(this), "data-page");
        searchFunction(p);
    });

    function objitem(){
        var caseno = MODAhtmlEncode($("#caseno"),"val");
        var strDate = MODAhtmlEncode($("#strDate"),"val");
        var endDate = MODAhtmlEncode($("#endDate"),"val");
        var DisplayCount = 15;
        if( MODAhtmlEncode($('#perPageShow'),"val") != null) DisplayCount = MODAhtmlEncode($('#perPageShow'),"val");

        var selectobj = {
            "caseno":caseno,
            "displayCount": DisplayCount,
            "strDate": strDate,
            "endDate": endDate
        };
        return selectobj ;
    }
    function searchFunction(p) {
        $('.preloader').show();
        var selectobj =objitem();
        var getUrl = "?strDate="+selectobj.strDate+"&endDate=" + selectobj.endDate + "&p=" + p + "&displayCount=" + selectobj.displayCount+"&cn="+selectobj.caseno;
        var pageUrl = href + getUrl;
        reloadDataTable(pageUrl);
    }
    function reloadDataTable(href) {
        $("#tableList").html("");
        $("#tableList").load(href, function () {
            $('.preloader').hide();
        });
    }
    function exportFun()
    {
        var selectobj =objitem();
        var _export = "@Url.Action("ExcelReport", "SpeedLog", new { area = "MailBox" })";
        var getUrl = "?strDate="+selectobj.strDate+"&endDate=" + selectobj.endDate+"&cn="+selectobj.caseno;;
        var exportUrl = _export + getUrl;
        location.href = exportUrl;
    }
</script>
}

Management/Areas/MailBox/Views/SpeedLog/List.cshtml
@model Management.Areas.MailBox.Models.SpeedLog.ListModel
@{
    int row = ((Model.defaultPager.p - 1) * Model.defaultPager.DisplayCount) == 0 ? 1 : ((Model.defaultPager.p - 1) * Model.defaultPager.DisplayCount) + 1;
}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="white-space:nowrap;" class="colW1">序號</th>
            <th scope="col" class="colW4">案件編號</th>
            <th scope="col" class="colW4">API請求</th>
            <th scope="col" class="colW4">請求狀態</th>
            <th scope="col" class="colW4">API回應狀態</th>
            <th scope="col" class="colW4">請求時間</th>
            <th scope="col">使用者</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.SpeedLogs?.Count > 0)
        {
            @foreach (var data in Model?.SpeedLogs)
            {

                <tr>
                    <td>@row</td>
                    <td>@data.CaseNo</td>
                    <td>@data.Action</td>
                    <td>@data.Success</td>
                    <td>@data.ApiStatus</td>
                    <td>@data.CreateDate.ToString("yyyy-MM-dd HH:mm")</td>
                    <td>@data.CreateUser</td>          
                </tr>
                row++;
            }
        }
        else
        {
            <tr>
                <td colspan="7">@Utility.SysConstTable.ListNotFound.TW</td>
            </tr>
        }
    </tbody>
</table>
@* 頁碼功能- id =pager   *@
@if (Model?.SpeedLogs.Count > 0)
{
    <div id="pager">
        <partial name="~/Views/Common/Pagination.cshtml" model="@Model.defaultPager" />
    </div>
}