Management/Areas/WebManagement/Controllers/BrowseStatisticsController.cs
using Google.Analytics.Data.V1Beta;
using Management.Areas.WebManagement.Models.OperationStatistics;
using Management.ManagementUtility;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Services.WebManagement;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Utility;

namespace Management.Areas.WebManagement.Controllers
{
    [Area("WebManagement")]
    public class BrowseStatisticsController : BaseController
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        public BrowseStatisticsController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            ViewData["Breadcrumb"] = CommonUtility.Breadcrumb(15);
            if (!CheckUserMenu(21).chk) { return RedirectToAction("ErrorCome", "Home", new { area = "" }); }
            return View();
        }

        public IActionResult IndexF()
        {
            ViewData["Breadcrumb"] = CommonUtility.Breadcrumb(21);
            if (!CheckUserMenu(21).chk) { return RedirectToAction("ErrorCome", "Home", new { area = "" }); }
            return View();
        }

        public IActionResult List(string sd, string ed, string websiteid, string key, int p = 1, int DisplayCount = 15)
        {
            string str = Convert.ToDateTime(sd).ToString("yyyy-MM-dd 00:00:00").ToString();
            string end = Convert.ToDateTime(ed).ToString("yyyy-MM-dd 23:59:59").ToString();

            DefaultPager pager = new DefaultPager
            {
                DisplayCount = DisplayCount,
                p = p
            };

            var data = BrowseStatisticsService.GetFilesCount(websiteid, str, end, key, ref pager);

            Models.OperationStatistics.ListModel listModel = new Models.OperationStatistics.ListModel
            {
                defaultPager = pager,
                BrowseStatisticsModels = data
            };

            return View(listModel);
        }

        public IActionResult Export(string sd, string ed, string websiteid, string key)
        {
            try
            {
                string str = Convert.ToDateTime(sd).ToString("yyyy-MM-dd 00:00:00").ToString();
                string end = Convert.ToDateTime(ed).ToString("yyyy-MM-dd 23:59:59").ToString();
                var fpath = _hostingEnvironment.WebRootPath;
                var excelDatas = new MemoryStream();
                var data = BrowseStatisticsService.GetFileData(websiteid, str, end, key);
                var filePath = $@"{fpath}/Temp/ExampleReport.xlsx";
                var Info = new List<string>() {
                $@"建表日期: {DateTime.UtcNow.AddHours(8).ToString("yyyy-MM-dd HH:mm")}",
                $@"建表人: {UserData?.sysUser.UserName}",
                $@"月份：{sd}至{ed}"
                };

                var DetailTitle = new List<string>() {
                "編號",
                "檔案標題",
                "檔案路徑",
                "檔案下載數"
                };

                var EModel = new ExcelModel();
                EModel.Info = Info;
                EModel.DetailTitle = DetailTitle;

                var Lang = new List<string>()
                {
                    "ZH-TW",
                    "EN"
                };

                var WEBSite = string.IsNullOrEmpty(websiteid) ? Services.WebSite.HomeService.GetSysWebSite().Select(x => new[] { x.WebSiteID, x.Title }).ToList() : Services.WebSite.HomeService.GetSysWebSite().Where(x => x.WebSiteID == websiteid).Select(x => new[] { x.WebSiteID, x.Title }).ToList();


                EModel.ExcelDetails = data.Select(x => new ExcelDetailModel()
                {
                    a = x.OriginalFileName,
                    b = x.Path,
                    c = x.DownLoadCount.ToString(),
                    d = x.Lang,
                    e = x.WEBSiteID
                }).ToList();

                excelDatas = Utility.Output.SheetReportByFile(filePath, EModel, Lang, WEBSite);

                SetSession("file", Convert.ToBase64String(excelDatas.ToArray()));

                excelDatas.Dispose();

                return StatusResult(System.Net.HttpStatusCode.OK, "");


            }
            catch (Exception ex)
            {
                IList<string> errmsgs = new List<string>();
                string error = "";
                error = ex.Message;
                errmsgs.Add(error);

                SetSession("file", Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(error)));

                return StatusResult(System.Net.HttpStatusCode.BadRequest, "");

            }
        }

        [HttpGet]
        public IActionResult Download()
        {
            byte[] data = Convert.FromBase64String(GetSession<string>("file"));
            var fileName = $@"檔案下載統計數{DateTime.UtcNow.AddHours(8):yyyyMMdd}.xlsx";
            return File(data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"{fileName}");
        }

        public IActionResult ListG(string SD, string ED, string website, string lan)
        {
            SetSession("ga4Data", null);
            var fpath = _hostingEnvironment.WebRootPath;
            var filePath = $@"{fpath}/Oauth/brave-attic.json";
            var ga4 = $@"{fpath}/Oauth/GA4.json";
            DateTime str = Convert.ToDateTime(SD);
            DateTime end = Convert.ToDateTime(ED);
            GAViewModel gA = new GAViewModel();
            GA4 items = new GA4();
            try
            {
                using (StreamReader r = new StreamReader(ga4))
                {
                    string json = r.ReadToEnd();
                    items = JsonConvert.DeserializeObject<GA4>(json);
                }
                if (items.data.Count > 0)
                {
                    var GAid = items.data.Where(x => x.WebSiteID == website && x.Language == lan.ToUpper()).FirstOrDefault();
                    if (GAid != null)
                    {
                        BetaAnalyticsDataClient client = new BetaAnalyticsDataClientBuilder
                        {
                            CredentialsPath = filePath
                        }.Build();

                        gA.Flow2Data = GetFlow2(str, end, client, GAid.GA4);
                        gA.Flow2Data.chartName = "訪客流量";
                        gA.Flow2Data.chartId = "flowChart";
                        gA.CountryModels = GetMap2(str, end, client, GAid.GA4);
                        gA.Country2Data = GetCountry2(str, end, client, GAid.GA4);
                        gA.Country2Data.chartName = "訪客來源國家";
                        gA.Country2Data.chartId = "countryChart";
                        gA.City2Data = GetCity2(str, end, client, GAid.GA4);
                        gA.City2Data.chartName = "臺灣地區";
                        gA.City2Data.chartId = "cityChart";
                        gA.HotData = GetPagePath2(str, end, client, GAid.GA4, "hot");
                        gA.HotData.chartName = "熱門單元排行";
                        gA.HotData.chartId = "hotChart";
                        gA.ColdData = GetPagePath2(str, end, client, GAid.GA4, "cold");
                        gA.ColdData.chartName = "冷門單元排行";
                        gA.ColdData.chartId = "coldChart";
                    }
                    else
                    {
                        gA.Name = "目前還未設定GA4相關資料，請洽管理員處理";
                    }
                }
                else
                {
                    gA.Name = "目前還未設定GA4相關資料，請洽管理員處理";
                }
                return View(gA);
            }
            catch (Exception ex)
            {
                gA.Name = "目前還未與GA4連結，請洽管理員處理";
                return View(gA);
            }
        }
        #region GA4報表資料
        /// <summary>
        /// 顏色
        /// </summary>
        static List<string> backgroundColor = new List<string>() {
 "#ff6384"
,"#ff9f40"
,"#ffcd56"
,"#7ac142"
,"#4bc0c0"
,"#36a2eb"
,"#8a8acb"
,"#a37df0"
,"#a98c66"
,"#bdbdbd"
        };
        /// <summary>
        /// 新舊使用者
        /// </summary>
        /// <param name="SD"></param>
        /// <param name="ED"></param>
        /// <param name="client"></param>
        /// <param name="GAid"></param>
        /// <returns></returns>
        public ChartModel GetFlow2(DateTime SD, DateTime ED, BetaAnalyticsDataClient client, string GAid)
        {
            #region GA4資料來源
            var date = new List<string>();
            for (var d = SD; d <= ED; d = d.AddDays(1))
            {
                date.Add(d.ToString("yyyy-MM-dd"));
            }
            var request = new RunReportRequest
            {
                Property = "properties/" + GAid,
                Dimensions = { new Dimension { Name = "date" } },
                Metrics = { new Metric { Name = "totalUsers" }, new Metric { Name = "newUsers" } },
                DateRanges = { new DateRange { StartDate = SD.ToString("yyyy-MM-dd"), EndDate = ED.ToString("yyyy-MM-dd") }, },
                OrderBys = { new OrderBy { Dimension = new OrderBy.Types.DimensionOrderBy() { DimensionName = "date" }, Desc = false }, }
            };
            var response = client.RunReport(request);
            #endregion
            ChartModel flow2 = new ChartModel();
            flow2.chartype = EnumChart.mixed;
            flow2.labels = date;
            flow2.datasets = new List<ChartDatasets>();
            if (response.Rows.Count > 0)
            {

                for (var i = 0; i < response.MetricHeaders.Count; i++)
                {
                    ChartDatasets charDatasets = new ChartDatasets();
                    charDatasets.type = "line";
                    charDatasets.label = $@"{ (i > 0 ? "新" : "")}使用者";
                    charDatasets.data = new List<int>();
                    charDatasets.backgroundColor = backgroundColor.Skip(i).Take(1).ToList();

Management/Areas/WebManagement/Views/BrowseStatistics/ChartTemplate.cshtml
@model Management.Areas.WebManagement.Models.OperationStatistics.ChartModel 
@{
    var md = Model;
}
<canvas id="@md.chartId"></canvas>
<script>
       var ctx = document.getElementById('@md.chartId');
       var Cdata = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(md))' );
       var options;
       var chartType ='@(Utility.EnumTpye.GetEnumName(md.chartype))';
       switch(chartType)
       {
           case 'bar':
            options = {
                indexAxis: 'y',
                datalabels: chartLabel,
                plugins:{
                    title: {
                        display: true,
                        text: '@Html.Raw(md.chartName)',
                    }
                }
           };
           break;
           case 'mixed':
            options =   {
                scales: { y: {beginAtZero: true }},
                plugins :{
                    title: {
                    display: true,
                    text: '@Html.Raw(md.chartName)',
                    }
                }
            }
           break;
       }

       hotChart = new Chart(ctx, {
        type: chartType,
        data: Cdata,
        plugins: [ChartDataLabels], //增加這行
        options: options
        });
        var obj = {
         id :'@md.chartId',
         chart : hotChart
        };
        ChartObject.push( obj);

</script>

Management/Areas/WebManagement/Views/BrowseStatistics/Country.cshtml
<canvas id="Country"></canvas>

<script>
    var ctx = document.getElementById('Country');

   countryChart = new Chart(ctx, {
   type: _ChratData.country.type,
   data: _ChratData.country.data,
   plugins: [ChartDataLabels], //增加這行
   options: _ChratData.country.options
});
</script>

Management/Areas/WebManagement/Views/BrowseStatistics/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <div class="row searchBar1">
                <div class="col">
                    <label class="col-form-label">
                        語系：
                    </label>
                    <select id="language" name="language" class="form-control">
                        <option value="zh-tw" selected>中文</option>
                        <option value="en">英文</option>
                    </select>
                </div>
                <div class="col col-dateToDate">
                    <label class="col-form-label">
                        日期區間：
                    </label>
                    <div class="row">
                        <div class="col">
                            <input type="date" id="sddate" class="form-control" placeholder="" value="">
                        </div>
                        <div class="col">~</div>
                        <div class="col">
                            <input type="date" id="eddate" class="form-control" placeholder="" value="">
                        </div>
                        <div class="col">
                            @{
                                var btns = new List<btnModel>()
                            {
                            new btnModel(){   Btntype = btnModel.btntype.查詢, onclickFunction="search()",jsUseClassName="search"  }
                            };
                                <partial name="~/Views/Common/Btn/BtnPublicVersion.cshtml" model="btns" />
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div id="tableList"></div>
        </div>
    </div>
</div>
<script>

    var href = "@Url.Action("ListG", "BrowseStatistics", new { area = "WebManagement" })";
    function search() {
        $('.preloader').show();
        var sd = MODAhtmlEncode($("#sddate"), "val");
        var ed = MODAhtmlEncode($("#eddate"), "val");
        var lang = MODASelectVal("language");
        var website = MODAhtmlEncode($("#drlWebSite"), "val");
        if (sd != "" && ed != "") {
            if (ed < sd) {
                Swal.fire({
                    icon: "warning",
                    title: "請輸入開始日期大於結束日期"
                });
            }
            else {
                var getUrl = "?sd=" + sd + "&ed=" + ed + "&website=" + website + "&lan=" + lang;
                var pageUrl = href + getUrl;
                reloadDataTable(pageUrl);
            }
        }
        else {
            Swal.fire({
                icon: "warning",
                title: "請輸入月份"
            });
        }
    }
    function reloadDataTable(href) {
        $("#tableList").html("");
        $("#tableList").load(href, function() {
        $('.preloader').hide();
        });
    }

    $("#language").change(function() {
        lan = $("#language option:selected").val();
    });

</script>

Management/Areas/WebManagement/Views/BrowseStatistics/IndexF.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var website = Services.WebSite.HomeService.GetSysWebSite();
}

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <h2 class="font-weight-bold mt-0">檔案下載統計</h2>

            <div class="row searchBar1">
                <div class="col">
                    <label class="col-form-label">
                        關鍵字：
                    </label>
                    <input type="text" id="keyword" class="form-control" placeholder="關鍵字">
                </div>
                <div class="col">
                    <label class="col-form-label">
                        站台：
                    </label>
                    <select class="form-control" name="websiteid">
                        <option value="">--請選擇--</option>
                        @foreach (var data in website)
                        {
                            <option value="@data.WebSiteID">@data.Title</option>
                        }
                    </select>
                </div>
                <div class="col col-dateToDate">
                    <label class="col-form-label">
                        日期區間：
                    </label>
                    <div class="row">
                        <div class="col">
                            <input type="date" id="sddate" class="form-control" placeholder="" value="" min="2022-12-01">
                        </div>
                        <div class="col">~</div>
                        <div class="col">
                            <input type="date" id="eddate" class="form-control" placeholder="" value="" disabled>
                        </div>
                        <div class="col">
                            @{
                                var btns = new List<btnModel>()
                            {
                            new btnModel(){   Btntype = btnModel.btntype.查詢, onclickFunction="searchFunction(1)",jsUseClassName="search"  },
                            new btnModel(){   Btntype = btnModel.btntype.匯出, onclickFunction="Export()", jsUseClassName="output"  }
                            };
                                                <partial name="~/Views/Common/Btn/BtnPublicVersion.cshtml" model="btns" />
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="bootstrap-table">
                <div id="tableList">
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var href = "@Url.Action("List", "BrowseStatistics", new { area = "WebManagement" })";

    function searchFunction(p) {
        var sd = MODAhtmlEncode($("#sddate"), "val");
        var ed = MODAhtmlEncode($("#eddate"), "val");
        var keyword = MODAhtmlEncode($("#keyword"), "val");
        var websiteid = chkwebsiteid(MODASelectVal("websiteid"));

        var Diff = DateDiff(sd, ed);

        if (sd != "" && ed != "") {
            if (ed < sd) {
                Swal.fire({
                    icon: "warning",
                    title: "請輸入開始日期大於結束日期"
                });
            }
            else if (Diff > 183) {
                Swal.fire({
                    icon: "warning",
                    title: "查詢區間限制為六個月內，請重新選擇起迄日。"
                });
            }
            else {
                var getUrl = "?sd=" + sd + "&ed=" + ed + "&websiteid=" + websiteid + "&key=" + keyword + "&p=" + p;
                var pageUrl = href + getUrl;
                reloadDataTable(pageUrl);
            }
        }
        else {
            Swal.fire({
                icon: "warning",
                title: "請輸入月份"
            });
        }
    }

    function reloadDataTable(href) {
        $("#tableList").html("");
        $("#tableList").load(href, function() {
            $(document).off('click', '.page_a');
            $(document).on("click", ".page_a", function() {
                var p = getObjAtr($(this), "data-page");
                searchFunction(p);
            });
        });
    }

    function chkwebsiteid(txt) {
        switch (txt) {
            case "MODA": return txt; break;
            case "ACS": return txt; break;
            case "ADI": return txt; break;
            default: return ""; break;
        }
    }

    function Export() {
        var sd = MODAhtmlEncode($("#sddate"), "val");
        var ed = MODAhtmlEncode($("#eddate"), "val");
        var websiteid = chkwebsiteid(MODASelectVal("websiteid"));
        var keyword = MODAhtmlEncode($("#keyword"), "val");

        var Diff = DateDiff(sd, ed);

        if (sd != "" && ed != "") {
            if (ed < sd) {
                Swal.fire({
                    icon: "warning",
                    title: "請輸入開始日期大於結束日期"
                });
            }
            else if (Diff > 183) {
                Swal.fire({
                    icon: "warning",
                    title: "查詢區間限制為六個月內，請重新選擇起迄日。"
                });
            }
            else {
                var href = '@Url.Action("Export", "BrowseStatistics", new {area= "WebManagement" })';
                Swal.fire({
                    title: '報表產生中 請耐心等待',
                    icon: 'warning',
                    showDenyButton: true,
                    showCancelButton: false,
                    confirmButtonText: '確定',
                    denyButtonText: '取消',
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: href,
                            type: 'POST',
                            data: {
                                sd: sd,
                                ed: ed,
                                websiteid: websiteid,
                                key: keyword,
                            },
                            beforeSend: function() {
                                $('.preloader').show();
                            },
                            success: function(data) {
                                location.href = '@Url.Action("Download", "BrowseStatistics", new {area= "WebManagement" })';
                            },
                            complete: function() {
                                $('.preloader').hide();
                            }
                        });
                    } else if (result.isDenied) {
                        Swal.fire('已取消!', '', 'info')
                    }
                })
            }
        }
        else {
            Swal.fire({
                icon: "warning",
                title: "請輸入月份"
            });
        }
    }

    $('#sddate').change(function() {
        var sd = $("#sddate").val();       
        $("#eddate").val('');
        $("#eddate").val(sd);
        var ed = new Date(sd);
        ed.setDate(ed.getDate() + 183);
        if (sd == "") {
            $("#eddate").prop('disabled', true);
        }
        else {
            $("#eddate").prop('disabled', false);
            $("#eddate").attr('max', ed.toISOString().split("T")[0]);
        }
    })

    var DateDiff = function(SD, ED) {
        var oDate1 = new Date(SD);
        var oDate2 = new Date(ED);
        var iDays = parseInt(Math.abs(oDate1 - oDate2) / 1000 / 60 / 60 / 24);
        return iDays;
    };

</script>

Management/Areas/WebManagement/Views/BrowseStatistics/List.cshtml
@model Management.Areas.WebManagement.Models.OperationStatistics.ListModel
@{
    int row = ((Model.defaultPager.p - 1) * Model.defaultPager.DisplayCount) == 0 ? 1 : ((Model.defaultPager.p - 1) * Model.defaultPager.DisplayCount) + 1;
}

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col" style="white-space:nowrap;" class="colW1">序號</th>
            <th scope="col" class="colW8">檔案名稱</th>
            <th scope="col">檔案路徑</th>
            <th scope="col" class="colW3">檔案下載數</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.BrowseStatisticsModels.Count > 0)
        {
            @foreach (var data in Model.BrowseStatisticsModels)
            {
                <tr>
                    <td>@row</td>
                    <td class="text-break text-start">@data.OriginalFileName</td>
                    <td align="left">@data.Path</td>
                    <td>@data.DownLoadCount</td>
                </tr>
                row++;
            }
        }
        else
        {
            <tr>
                <td colspan="4">@Utility.SysConstTable.ListNotFound.TW</td>
            </tr>
        }
    </tbody>
</table>
@* 頁碼功能- id =pager   *@
<div id="pager">
    <partial name="~/Views/Common/Pagination.cshtml" model="@Model.defaultPager" />
</div>

Management/Areas/WebManagement/Views/BrowseStatistics/Map.cshtml
@model List<Management.Areas.WebManagement.Models.OperationStatistics.CountryModel>
@{
    var md = Model;
}
<style type="text/css">
    #legend {
        font-weight: 700;
        fill:#666;
    }
    #legend g text{
        font-size: 0.8em;
    }
    .map {
        background-color: #FFFFFF;
        overflow-x: auto;
    }
    .map path{
        cursor: pointer;
    }
    .background {
        fill: transparent;
        pointer-evens: all;
    }
    .world {
        transform-origin: center;
    }
    div.tooltip {
        position: absolute;
        padding: 7px;
        font-size: 0.8em;
        pointer-events: none;
        background: #fff;
        border: 1px solid #e6e6e6;
        border-radius: 4px;
        box-shadow: 3px 3px 5px 0px rgba(0, 0, 0, 0.1);
    }
</style>
<div class="map">
    <svg id="my_dataviz" width="1000" height="563"></svg>
</div>
<script>
    var svg = d3.select("svg");
    var width = svg.attr("width");
    var height = svg.attr("height");
    var path = d3.geoPath();
    var data = d3.map();
    var worldmap = "@Url.Action("GetGeoJson","BrowseStatistics",new {area="WebManagement"})";
  //  var worldmap = "https://raw.githubusercontent.com/holtzy/D3-graph-gallery/master/DATA/world.geojson";
   
    T1data = JSON.parse('@Html.Raw(JsonConvert.SerializeObject(md))' );
    var centered, world;

    function CreateData()
    {
        T1data.forEach(function(e){
        data.set(e.code, +e.pop);
    });
    }
    CreateData();
    // style of geographic projection and scaling
    var projection = d3.geoRobinson()
        .scale(161)
        .translate([width / 2, height / 2]);
    // Define color scale
    var colorScale = d3.scaleThreshold()
        .domain([10, 100, 1000, 20000, 30000, 40000, 50000])
        .range(['#dddddd','#ead0a9','#a4b3d5','#b8e076','#85ceb7','#ffe159','#fda481','#e67c73']);

    // add tooltip
    var tooltip = d3.select("body").append("div")
        .attr("class", "tooltip")
        .style("opacity", 0);

    // Load external data and boot
    d3.queue()
        .defer(d3.json, worldmap)
        .await(ready);

    // Add clickable background
    svg.append("rect")
        .attr("class", "background")
        .attr("width", width)
        .attr("height", height)
        .on("click", click);


      // ----------------------------
      //Start of Choropleth drawing
      // ----------------------------

    function ready(error, topo) {
        // topo is the data received from the d3.queue function (the world.geojson)
        // the data from world_population.csv (country code and country population) is saved in data variable
        var mouseOver = function(d) {
            d3.selectAll(".Country")
                .transition()
                .duration(200)
                .style("opacity", .5)
                .style("stroke", "transparent");
            d3.select(this)
                .transition()
                .duration(200)
                .style("opacity", 1)
                .style("stroke", "black");
            tooltip.style("left", (d3.event.pageX + 15) + "px")
                .style("top", (d3.event.pageY - 28) + "px")
                .transition().duration(400)
                .style("opacity", 1)
                .text(d.properties.name + '：' + d.total);
        }

        var mouseLeave = function() {
            d3.selectAll(".Country")
                .transition()
                .duration(200)
                .style("opacity", 1)
                .style("stroke", "transparent");
            tooltip.transition().duration(300)
                .style("opacity", 0);
        }

        // Draw the map
        world = svg.append("g")
        .attr("class", "world");
        world.selectAll("path")
            .data(topo.features)
            .enter()
            .append("path")
            // draw each country
            // d3.geoPath() is a built-in function of d3 v4 and takes care of showing the map from a properly formatted geojson file, if necessary filtering it through a predefined geographic projection
            .attr("d", d3.geoPath().projection(projection))

            //retrieve the name of the country from data
            .attr("data-name", function(d) {
                return d.properties.name
            })

            // set the color of each country
            .attr("fill", function(d) {
                d.total = data.get(d.id) || 0;
                return colorScale(d.total);
            })

            // add a class, styling and mouseover/mouseleave and click functions
            .style("stroke", "transparent")
            .attr("class", function(d) {
                return "Country"
            })
            .attr("id", function(d) {
                return d.id
            })
            .style("opacity", 1)
            .on("mouseover", mouseOver)
            .on("mouseleave", mouseLeave)
            .on("click", click);

        // Legend
        var x = d3.scaleLinear()
            .domain([2.6, 75.1])
            .rangeRound([600, 860]);

        var legend = svg.append("g")
            .attr("id", "legend");

        var legend_entry = legend.selectAll("g.legend")
            .data(colorScale.range().map(function(d) {
                d = colorScale.invertExtent(d);
                if (d[0] == null) d[0] = x.domain()[0];
                if (d[1] == null) d[1] = x.domain()[1];
                return d;
            }))
            .enter().append("g")
            .attr("class", "legend_entry");

        var ls_w = 20,
            ls_h = 20;

        legend_entry.append("rect")
            .attr("x", 0)
            .attr("y", function(d, i) {
                return height - (i * ls_h) - ls_h;
            })
            .attr("width", ls_w)
            .attr("height", ls_h)
            .style("fill", function(d) {
                return colorScale(d[0]);
            })
            .style("opacity", 0.8);

        legend_entry.append("text")
            .attr("x", 30)
            .attr("y", function(d, i) {
                return height - (i * ls_h) - 6;
            })
            .text(function(d, i) {
                if (i === 0) return "< " + d[1];
                if (d[1] < d[0]) return "> "+ d[0];
                return d[0] + " - " + d[1];
            });

        legend.append("text").attr("x", 0).attr("y", function(d,i){
            return height - (ls_h * 8) - 15;
        }).text("瀏覽人次");
    }

    // Zoom functionality
    function click(d) {
    var x, y, k;

    if (d && centered !== d) {
        var centroid = path.centroid(d);
        x = -(centroid[0] * 6);
        y = (centroid[1] * 6);
        k = 3;
        centered = d;
    } else {
        x = 0;
        y = 0;
        k = 1;
        centered = null;
    }

    world.selectAll("path")
        .classed("active", centered && function(d) { return d === centered; });

    world.transition()
        .duration(750)
        .attr("transform", "translate(" + x + "," + y + ") scale(" + k + ")" );

    }


</script>